version: '2'
services:
  rabbitmq:
      image: rabbitmq:management
      restart: always
      ports:
        - 15673:15672
  registry:
    image: kaisagroup_plateform/kaisagroup_eureka
    ports:
      - "9003:9003"
  config:
    image: kaisagroup_plateform/kaisagroup_conf
    ports:
      - "9004:9004"
  monitor:
    image: kaisagroup_plateform/kaisagroup_admin
    ports:
      - "9002:9002"
  zipkin:
    image: kaisagroup_plateform/kaisagroup_sleuth
    ports:
      - "9001:9001"
  gateway:
    image: kaisagroup_plateform/kaisagroup_zuul
    ports:
      - "9005:9005"
#  auth-service:
#    image: kaisagroup_plateform/auth-service
#    ports:
#      - "5000:5000"
#  testa-service:
#    image: kaisagroup_micro/testa-service
#  testb-service:
#    image: kaisagroup_micro/testb-service