version: '2'
services:
  rabbitmq:
      image: rabbitmq:management
      restart: always
      ports:
        - 15673:9019
  eureka:
      image: kaisagroup_eureka
      ports:
        - "9003:9003"
  config:
      image: kaisagroup_conf
      ports:
        - "9004:9004"
  sleuth:
      image: kaisagroup_sleuth
      ports:
        - "9001:9001"
  admin:
      image: kaisagroup_admin
      ports:
        - "9002:9002"
  zuul:
      image: kaisagroup_zuul
      ports:
        - "9011:9011"
  user:
      image: kaisagrop_user
      ports:
        - "8024:8024"
#  auth-service:
#    image: auth-service
#    ports:
#      - "5000:5000"
#  testa-service:
#    image: testa-service
#  testb-service:
#    image: testb-service