version: '2'
services:
  rabbitmq:
      image: rabbitmq:management
      restart: always
      ports:
        - 15673:15672
  eureka:
    image: kaisagroup_plateform/kaisagroup_eureka
    restart: always
    ports:
      - "9003:9003"
  config:
    image: kaisagroup_plateform/kaisagroup_conf
    restart: always
    ports:
      - "9004:9004"
  sleuth:
      image: kaisagroup_plateform/kaisagroup_sleuth
      restart: always
      ports:
        - "9001:9001"
  admin:
    image: kaisagroup_plateform/kaisagroup_admin
    restart: always
    ports:
      - "9002:9002"
  zuul:
    image: kaisagroup_plateform/kaisagroup_zuul
    restart: always
    ports:
      - "9005:9005"
#  auth-service:
#    image: kaisagroup_plateform/auth-service
#    ports:
#      - "5000:5000"
#  testa-service:
#    image: kaisagroup_micro/testa-service
#  testb-service:
#    image: kaisagroup_micro/testb-service