server:
  port: 9011

management:
  security:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

zuul:
  ignoredServices: '*'
  routes:
    msg-service:
      path: /msg/**
      stripPrefix: false
      sensitiveHeaders:

spring:
  mvc:
    view:
      prefix: /templates/
      suffix: .ftl
  freemarker:
    cache: false
    request-context-attribute: request
  boot:
    admin:
      url: http://localhost:9002
  zipkin:
    base-url: http://localhost:9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9003/eureka/
